# Force vendoring of k8s code-generator
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/gengo/args",
]

# Disable removal of runtime-unused code-generator
[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  go-tests = false
  unused-packages = false

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "github.com/hetznercloud/hcloud-go"
  version = "v1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.10.2"