[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[constraint]]
  name = "github.com/hetznercloud/hcloud-go"
  version = "v1.7.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "github.com/spotahome/kooper"
  branch = "master"