---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-floating-ip-controller
rules:
- apiGroups:
    - ""
  resources: 
    - nodes
  verbs: 
    - get
    - watch
    - list
- apiGroups: ["hcloud.apricote.de"]
  resources:
    - floatingips
  verbs:
    - get
    - watch
    - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-floating-ip-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hcloud-floating-ip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewahcloud-floating-ip-controllertch
subjects:
  - kind: ServiceAccount
    name: hcloud-floating-ip-controller
    namespace: kube-system